import type { CSSProperties } from "react";
import { createRoot } from "react-dom/client";
import { toJpeg } from "html-to-image";
import jsPDF from "jspdf";
import type { MaintenanceEvent, MaintenanceMetric } from "@/lib/queries";
import { TYPE_LABELS, STATUS_LABELS, formatDuration, formatHours, sortByWorstMtbf } from "@/lib/maintenance-format";

const LOGO_MAX_HEIGHT = 36; // pt
const PAGE_MARGIN = 24; // pt
const FOOTER_HEIGHT = 24; // pt — reserved at the bottom of every page
const SECTION_GAP = 12; // pt
const JPEG_QUALITY = 0.85;
const CAPTURE_PIXEL_RATIO = 1.5;
// Narrower than the main dashboard export (1280px) — this report is a
// handful of dense tables/cards, not a full dashboard of charts, and
// doesn't need to match any live viewport since it's built off-screen
// specifically for this export.
const CAPTURE_WIDTH = 1000; // px

export interface MaintenanceReportOptions {
  lineName: string;
  from: string | null;
  to: string | null;
  // Display name (or email fallback) of the user who triggered the export —
  // shown in the page-1 header as "Generated by", distinct from the
  // generation timestamp.
  generatedBy: string;
  // Currently-filtered events (line/type/status/date filters from the
  // /maintenance page) — this is the "what got exported" set, used for the
  // events table and the Mechanical vs Electrical downtime chart.
  events: MaintenanceEvent[];
  // Lifetime, unfiltered MTBF/MTTR by Line & Type — same semantics as the
  // live page's own metrics table (its own doc comment: "not affected by
  // the table filters above"), reused as-is for consistency.
  metrics: MaintenanceMetric[];
  // Plant-wide summary numbers, already computed by the caller (same values
  // as the live page's own top KPI cards) — this module only presents them,
  // it doesn't re-derive MTBF/MTTR math itself.
  totalEvents: number;
  openCount: number;
  // Preventive events are kept out of openCount (which feeds the same
  // mechanical/electrical-only reliability story as the KPI cards above it)
  // and shown as its own card instead — see MaintenanceType docs.
  openPreventiveCount: number;
  mtbfMechanicalHours: number | null;
  mttrMechanicalHours: number | null;
  mtbfElectricalHours: number | null;
  mttrElectricalHours: number | null;
  // Reliability Analytics numbers — the exact same values already computed
  // by the live /maintenance page's own useMemo hooks (see
  // src/routes/maintenance.tsx), passed through rather than re-derived here,
  // so the report can never drift from what the page shows for the same
  // filter. topLossesByDowntime/topLossesByFrequency are sliced to the top 5
  // by the caller (or here, defensively); chronicVsSporadic is passed in
  // full so the summary counts below are accurate, not just the visible
  // slice.
  totalDowntimeMinutes: number;
  repeatFailureRatePct: number;
  availabilityPct: number | null;
  topLossesByDowntime: { title: string; totalMinutes: number }[];
  topLossesByFrequency: { title: string; count: number }[];
  chronicVsSporadic: { title: string; count: number; chronic: boolean }[];
  reliabilityByLine: { lineName: string; mtbfHours: number | null; mttrHours: number | null; availabilityPct: number | null; eventCount: number }[];
  onProgress?: (message: string) => void;
}

interface LogoInfo {
  dataUrl: string;
  widthPt: number;
  heightPt: number;
}

// Duplicated from pdf-export.ts rather than shared, deliberately — keeps
// this report isolated from the main dashboard exporter so a change to one
// can't regress the other. Same behavior: logo is optional, export proceeds
// without it if /logo.png can't be loaded.
async function loadLogo(): Promise<LogoInfo | null> {
  try {
    const res = await fetch("/logo.png");
    if (!res.ok) return null;
    const blob = await res.blob();
    const dataUrl: string = await new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result as string);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
    const img = await loadImage(dataUrl);
    const scale = img.height > LOGO_MAX_HEIGHT ? LOGO_MAX_HEIGHT / img.height : 1;
    return { dataUrl, widthPt: img.width * scale, heightPt: img.height * scale };
  } catch {
    return null;
  }
}

function loadImage(src: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => resolve(img);
    img.onerror = reject;
    img.src = src;
  });
}

// Same pixel-slicing fallback as pdf-export.ts, for a section (typically the
// events table, if the current filters match many rows) taller than one
// full page — always starts on its own fresh page so no other section
// shares the break, even though a table row could itself land on a slice
// boundary. Accepted tradeoff, same as the main dashboard exporter.
function drawOversizedSection(
  doc: jsPDF,
  img: HTMLImageElement,
  contentWidth: number,
  maxContentHeight: number,
  pxPerPt: number,
): void {
  let sourceY = 0;
  let remainingPx = img.height;
  let firstSlice = true;

  while (remainingPx > 0) {
    const availablePx = Math.floor(maxContentHeight * pxPerPt);
    const slicePx = Math.min(availablePx, remainingPx);

    const canvas = document.createElement("canvas");
    canvas.width = img.width;
    canvas.height = slicePx;
    const ctx = canvas.getContext("2d");
    if (!ctx) throw new Error("Canvas 2D context unavailable");
    ctx.drawImage(img, 0, sourceY, img.width, slicePx, 0, 0, img.width, slicePx);

    const sliceHeightPt = slicePx / pxPerPt;
    if (!firstSlice) doc.addPage();
    doc.addImage(
      canvas.toDataURL("image/jpeg", JPEG_QUALITY),
      "JPEG",
      PAGE_MARGIN,
      PAGE_MARGIN,
      contentWidth,
      sliceHeightPt,
      undefined,
      "FAST",
    );

    sourceY += slicePx;
    remainingPx -= slicePx;
    firstSlice = false;
  }
}

function eventDurationMinutes(e: MaintenanceEvent): number {
  const start = new Date(e.started_at).getTime();
  const end = e.resolved_at ? new Date(e.resolved_at).getTime() : Date.now();
  return Math.max(0, (end - start) / 60_000);
}

function personLabel(p: { display_name: string | null; email: string } | null): string {
  return p?.display_name || p?.email || "—";
}

// --- Report content, styled with plain hex colors rather than the app's
// Tailwind CSS-variable theme (bg-card, text-foreground, etc). This tree is
// rendered off-screen purely for capture, never shown live, so there's no
// reason for it to follow the exporting user's light/dark preference — a
// printed report should look the same regardless. Reusing <KpiCard> or the
// shadcn <Table> here would pull in theme variables that flip under a
// `.dark` ancestor class, which is exactly what this avoids. ---

const th: CSSProperties = {
  textAlign: "left",
  padding: "8px 10px",
  fontSize: 10,
  fontWeight: 700,
  textTransform: "uppercase",
  letterSpacing: 0.4,
  color: "#64748b",
  borderBottom: "2px solid #e2e8f0",
};
const td: CSSProperties = {
  padding: "8px 10px",
  fontSize: 12,
  color: "#1e293b",
  borderBottom: "1px solid #f1f5f9",
};

function ReportKpiCard({ label, value, accent }: { label: string; value: string; accent: string }) {
  return (
    <div style={{ border: "1px solid #e2e8f0", borderRadius: 10, padding: "14px 16px", background: "#ffffff" }}>
      <p style={{ margin: 0, fontSize: 10, fontWeight: 700, letterSpacing: 0.6, textTransform: "uppercase", color: "#64748b" }}>
        {label}
      </p>
      <p style={{ margin: "6px 0 0", fontSize: 22, fontWeight: 800, color: accent }}>{value}</p>
    </div>
  );
}

function DowntimeBar({ label, minutes, pct, color }: { label: string; minutes: number; pct: number; color: string }) {
  return (
    <div style={{ marginBottom: 18 }}>
      <div style={{ display: "flex", justifyContent: "space-between", fontSize: 13, marginBottom: 6 }}>
        <span style={{ fontWeight: 700, color: "#1e293b" }}>{label}</span>
        <span style={{ color: "#64748b" }}>
          {Math.round(minutes)} min · {pct.toFixed(1)}%
        </span>
      </div>
      <div style={{ height: 18, borderRadius: 6, background: "#f1f5f9", overflow: "hidden" }}>
        <div style={{ height: "100%", width: `${minutes > 0 ? Math.max(pct, 2) : 0}%`, background: color }} />
      </div>
    </div>
  );
}

// Same visual language as DowntimeBar but for a plain count rather than a
// minutes+percentage-of-whole pair (frequency bars compare "how many times"
// not "how much of the total").
function FrequencyBar({ label, count, pct, color }: { label: string; count: number; pct: number; color: string }) {
  return (
    <div style={{ marginBottom: 14 }}>
      <div style={{ display: "flex", justifyContent: "space-between", fontSize: 12, marginBottom: 4 }}>
        <span style={{ fontWeight: 700, color: "#1e293b" }}>{label}</span>
        <span style={{ color: "#64748b" }}>
          {count} event{count === 1 ? "" : "s"}
        </span>
      </div>
      <div style={{ height: 14, borderRadius: 6, background: "#f1f5f9", overflow: "hidden" }}>
        <div style={{ height: "100%", width: `${count > 0 ? Math.max(pct, 3) : 0}%`, background: color }} />
      </div>
    </div>
  );
}

function ReportLayout({
  events,
  metrics,
  totalEvents,
  openCount,
  openPreventiveCount,
  mtbfMechanicalHours,
  mttrMechanicalHours,
  mtbfElectricalHours,
  mttrElectricalHours,
  totalDowntimeMinutes,
  repeatFailureRatePct,
  availabilityPct,
  topLossesByDowntime,
  topLossesByFrequency,
  chronicVsSporadic,
  reliabilityByLine,
}: Pick<
  MaintenanceReportOptions,
  | "events"
  | "metrics"
  | "totalEvents"
  | "openCount"
  | "openPreventiveCount"
  | "mtbfMechanicalHours"
  | "mttrMechanicalHours"
  | "mtbfElectricalHours"
  | "mttrElectricalHours"
  | "totalDowntimeMinutes"
  | "repeatFailureRatePct"
  | "availabilityPct"
  | "topLossesByDowntime"
  | "topLossesByFrequency"
  | "chronicVsSporadic"
  | "reliabilityByLine"
>) {
  const mechMinutes = events.filter((e) => e.type === "mechanical").reduce((s, e) => s + eventDurationMinutes(e), 0);
  const elecMinutes = events.filter((e) => e.type === "electrical").reduce((s, e) => s + eventDurationMinutes(e), 0);
  const prevMinutes = events.filter((e) => e.type === "preventive").reduce((s, e) => s + eventDurationMinutes(e), 0);
  const totalMinutes = mechMinutes + elecMinutes + prevMinutes;
  const mechPct = totalMinutes > 0 ? (mechMinutes / totalMinutes) * 100 : 0;
  const elecPct = totalMinutes > 0 ? (elecMinutes / totalMinutes) * 100 : 0;
  const prevPct = totalMinutes > 0 ? (prevMinutes / totalMinutes) * 100 : 0;
  const sortedMetrics = sortByWorstMtbf(metrics);

  const top5Downtime = topLossesByDowntime.slice(0, 5);
  const top5Frequency = topLossesByFrequency.slice(0, 5);
  const chronicTitles = chronicVsSporadic.filter((t) => t.chronic);
  const sporadicTitles = chronicVsSporadic.filter((t) => !t.chronic);
  const chronicEventCount = chronicTitles.reduce((s, t) => s + t.count, 0);
  const sporadicEventCount = sporadicTitles.reduce((s, t) => s + t.count, 0);
  const topChronic = [...chronicTitles].sort((a, b) => b.count - a.count).slice(0, 5);

  return (
    <div style={{ width: CAPTURE_WIDTH, background: "#ffffff", fontFamily: "Arial, Helvetica, sans-serif", color: "#1e293b" }}>
      <div
        data-pdf-section="kpis"
        style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 12, padding: 20, background: "#ffffff" }}
      >
        <ReportKpiCard label="Total Events" value={String(totalEvents)} accent="#1e293b" />
        <ReportKpiCard label="Open" value={String(openCount)} accent={openCount > 0 ? "#d97706" : "#16a34a"} />
        <ReportKpiCard label="MTBF (Mechanical)" value={formatHours(mtbfMechanicalHours)} accent="#4f46e5" />
        <ReportKpiCard label="MTTR (Mechanical)" value={formatHours(mttrMechanicalHours)} accent="#4f46e5" />
        <ReportKpiCard label="MTBF (Electrical)" value={formatHours(mtbfElectricalHours)} accent="#f59e0b" />
        <ReportKpiCard label="MTTR (Electrical)" value={formatHours(mttrElectricalHours)} accent="#f59e0b" />
        <ReportKpiCard label="Open Preventive" value={String(openPreventiveCount)} accent={openPreventiveCount > 0 ? "#d97706" : "#16a34a"} />
      </div>

      <div
        data-pdf-section="chart"
        style={{ margin: "16px 20px", padding: 20, border: "1px solid #e2e8f0", borderRadius: 12, background: "#ffffff" }}
      >
        <p style={{ margin: "0 0 16px", fontSize: 15, fontWeight: 800 }}>Downtime by Type — Mechanical vs Electrical vs Preventive</p>
        {totalMinutes === 0 ? (
          <p style={{ fontSize: 12, color: "#64748b" }}>No downtime in the exported events.</p>
        ) : (
          <>
            <DowntimeBar label="Mechanical" minutes={mechMinutes} pct={mechPct} color="#4f46e5" />
            <DowntimeBar label="Electrical" minutes={elecMinutes} pct={elecPct} color="#f59e0b" />
            <DowntimeBar label="Preventive" minutes={prevMinutes} pct={prevPct} color="#16a34a" />
          </>
        )}
      </div>

      <div
        data-pdf-section="events-table"
        style={{ margin: "0 20px 16px", padding: 20, border: "1px solid #e2e8f0", borderRadius: 12, background: "#ffffff" }}
      >
        <p style={{ margin: "0 0 12px", fontSize: 15, fontWeight: 800 }}>Events ({events.length})</p>
        <table style={{ width: "100%", borderCollapse: "collapse" }}>
          <thead>
            <tr>
              <th style={th}>Event</th>
              <th style={th}>Type</th>
              <th style={th}>Severity</th>
              <th style={th}>Status</th>
              <th style={th}>Started</th>
              <th style={th}>Duration</th>
              <th style={th}>Technician</th>
              <th style={th}>Closed by</th>
            </tr>
          </thead>
          <tbody>
            {events.length === 0 ? (
              <tr>
                <td style={td} colSpan={8}>
                  No events match the current filters.
                </td>
              </tr>
            ) : (
              events.map((e) => (
                <tr key={e.id}>
                  <td style={td}>{e.title}</td>
                  <td style={td}>{TYPE_LABELS[e.type]}</td>
                  <td style={td}>{e.severity_label || "Unclassified"}</td>
                  <td style={td}>{STATUS_LABELS[e.status]}</td>
                  <td style={td}>{new Date(e.started_at).toLocaleString()}</td>
                  <td style={td}>
                    {formatDuration(
                      (e.resolved_at ? new Date(e.resolved_at).getTime() : Date.now()) - new Date(e.started_at).getTime(),
                    )}
                  </td>
                  <td style={td}>{e.technician_names.length > 0 ? e.technician_names.join(", ") : "—"}</td>
                  <td style={td}>{e.status === "resolved" ? personLabel(e.resolved_by_profile) : "—"}</td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      <div
        data-pdf-section="reliability-kpis"
        style={{ margin: "0 20px 16px", padding: 20, border: "1px solid #e2e8f0", borderRadius: 12, background: "#ffffff" }}
      >
        <p style={{ margin: "0 0 16px", fontSize: 15, fontWeight: 800 }}>Reliability Analytics</p>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 12 }}>
          <ReportKpiCard label="Maintenance Events Downtime" value={formatDuration(totalDowntimeMinutes * 60_000)} accent="#d97706" />
          <ReportKpiCard label="Repeat Failure Rate" value={`${repeatFailureRatePct.toFixed(1)}%`} accent="#dc2626" />
          <ReportKpiCard label="Equipment Availability" value={availabilityPct === null ? "—" : `${availabilityPct.toFixed(1)}%`} accent="#059669" />
        </div>
      </div>

      <div
        data-pdf-section="reliability-top-losses"
        style={{ margin: "0 20px 16px", padding: 20, border: "1px solid #e2e8f0", borderRadius: 12, background: "#ffffff" }}
      >
        <p style={{ margin: "0 0 12px", fontSize: 13, fontWeight: 800 }}>Top 5 Losses — By Downtime</p>
        {top5Downtime.length === 0 ? (
          <p style={{ fontSize: 12, color: "#64748b", marginBottom: 16 }}>No downtime in the exported events.</p>
        ) : (
          top5Downtime.map((t) => (
            <DowntimeBar
              key={t.title}
              label={t.title}
              minutes={t.totalMinutes}
              pct={totalDowntimeMinutes > 0 ? (t.totalMinutes / totalDowntimeMinutes) * 100 : 0}
              color="#ef4444"
            />
          ))
        )}
        <p style={{ margin: "8px 0 12px", fontSize: 13, fontWeight: 800 }}>Top 5 Losses — By Frequency</p>
        {top5Frequency.length === 0 ? (
          <p style={{ fontSize: 12, color: "#64748b" }}>No events in this export.</p>
        ) : (
          top5Frequency.map((t) => (
            <FrequencyBar
              key={t.title}
              label={t.title}
              count={t.count}
              pct={events.length > 0 ? (t.count / events.length) * 100 : 0}
              color="#3b82f6"
            />
          ))
        )}
      </div>

      <div
        data-pdf-section="reliability-chronic"
        style={{ margin: "0 20px 16px", padding: 20, border: "1px solid #e2e8f0", borderRadius: 12, background: "#ffffff" }}
      >
        <p style={{ margin: "0 0 4px", fontSize: 15, fontWeight: 800 }}>Chronic vs Sporadic Summary</p>
        <p style={{ margin: "0 0 12px", fontSize: 11, color: "#64748b" }}>Chronic = recurred + above-average duration.</p>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(2, 1fr)", gap: 12, marginBottom: 16 }}>
          <ReportKpiCard label="Chronic Faults" value={`${chronicTitles.length} titles · ${chronicEventCount} events`} accent="#dc2626" />
          <ReportKpiCard label="Sporadic Faults" value={`${sporadicTitles.length} titles · ${sporadicEventCount} events`} accent="#64748b" />
        </div>
        {topChronic.length > 0 && (
          <>
            <p style={{ margin: "0 0 8px", fontSize: 11, fontWeight: 700, color: "#64748b", textTransform: "uppercase" }}>
              Top Chronic Faults
            </p>
            <table style={{ width: "100%", borderCollapse: "collapse" }}>
              <thead>
                <tr>
                  <th style={th}>Title</th>
                  <th style={th}>Occurrences</th>
                </tr>
              </thead>
              <tbody>
                {topChronic.map((t) => (
                  <tr key={t.title}>
                    <td style={td}>{t.title}</td>
                    <td style={td}>{t.count}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </>
        )}
      </div>

      <div
        data-pdf-section="reliability-by-line"
        style={{ margin: "0 20px 16px", padding: 20, border: "1px solid #e2e8f0", borderRadius: 12, background: "#ffffff" }}
      >
        <p style={{ margin: "0 0 4px", fontSize: 15, fontWeight: 800 }}>Reliability by Line</p>
        <p style={{ margin: "0 0 12px", fontSize: 11, color: "#64748b" }}>Computed from the exported (currently filtered) events.</p>
        <table style={{ width: "100%", borderCollapse: "collapse" }}>
          <thead>
            <tr>
              <th style={th}>Line</th>
              <th style={th}>MTBF</th>
              <th style={th}>MTTR</th>
              <th style={th}>Equipment Availability</th>
              <th style={th}>Events</th>
            </tr>
          </thead>
          <tbody>
            {reliabilityByLine.length === 0 ? (
              <tr>
                <td style={td} colSpan={5}>
                  No events match the current filters.
                </td>
              </tr>
            ) : (
              reliabilityByLine.map((r) => (
                <tr key={r.lineName}>
                  <td style={td}>{r.lineName}</td>
                  <td style={td}>{formatHours(r.mtbfHours)}</td>
                  <td style={td}>{formatHours(r.mttrHours)}</td>
                  <td style={td}>{r.availabilityPct === null ? "—" : `${r.availabilityPct.toFixed(1)}%`}</td>
                  <td style={td}>{r.eventCount}</td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      <div
        data-pdf-section="metrics-table"
        style={{ margin: "0 20px 20px", padding: 20, border: "1px solid #e2e8f0", borderRadius: 12, background: "#ffffff" }}
      >
        <p style={{ margin: "0 0 4px", fontSize: 15, fontWeight: 800 }}>MTBF / MTTR by Line & Type</p>
        <p style={{ margin: "0 0 12px", fontSize: 11, color: "#64748b" }}>Lifetime reliability metrics, worst MTBF first.</p>
        <table style={{ width: "100%", borderCollapse: "collapse" }}>
          <thead>
            <tr>
              <th style={th}>Line</th>
              <th style={th}>Type</th>
              <th style={th}>MTBF</th>
              <th style={th}>MTTR</th>
              <th style={th}>Events</th>
              <th style={th}>Resolved</th>
            </tr>
          </thead>
          <tbody>
            {sortedMetrics.length === 0 ? (
              <tr>
                <td style={td} colSpan={6}>
                  No maintenance events recorded yet.
                </td>
              </tr>
            ) : (
              sortedMetrics.map((m) => (
                <tr key={`${m.line_id}-${m.type}`}>
                  <td style={td}>{m.line_name}</td>
                  <td style={td}>{TYPE_LABELS[m.type]}</td>
                  <td style={td}>{formatHours(m.mtbf_hours)}</td>
                  <td style={td}>{formatHours(m.mttr_hours)}</td>
                  <td style={td}>{m.event_count}</td>
                  <td style={td}>{m.resolved_count}</td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}

/**
 * Builds a Maintenance report as a PDF, mirroring pdf-export.ts's approach:
 * render real DOM (here, a React tree built off-screen specifically for the
 * export, not the live /maintenance page), screenshot each
 * `[data-pdf-section]` block with html-to-image, and lay each one into a
 * jsPDF document as an indivisible unit. Unlike the dashboard exporter, this
 * one also numbers every page ("Page X of Y") — the dashboard exporter only
 * ever produces a handful of tall sections, but a maintenance report can
 * span several pages of tabular data, so page numbers matter more here.
 */
export async function exportMaintenanceReportToPdf({
  lineName,
  from,
  to,
  generatedBy,
  events,
  metrics,
  totalEvents,
  openCount,
  openPreventiveCount,
  mtbfMechanicalHours,
  mttrMechanicalHours,
  mtbfElectricalHours,
  mttrElectricalHours,
  totalDowntimeMinutes,
  repeatFailureRatePct,
  availabilityPct,
  topLossesByDowntime,
  topLossesByFrequency,
  chronicVsSporadic,
  reliabilityByLine,
  onProgress,
}: MaintenanceReportOptions): Promise<void> {
  onProgress?.("Preparing report…");
  const logo = await loadLogo();
  const generatedAt = new Date();

  const hiddenContainer = document.createElement("div");
  hiddenContainer.style.position = "fixed";
  hiddenContainer.style.top = "0";
  hiddenContainer.style.left = "-99999px";
  document.body.appendChild(hiddenContainer);
  const root = createRoot(hiddenContainer);

  try {
    onProgress?.("Rendering report…");
    await new Promise<void>((resolve) => {
      root.render(
        <ReportLayout
          events={events}
          metrics={metrics}
          totalEvents={totalEvents}
          openCount={openCount}
          openPreventiveCount={openPreventiveCount}
          mtbfMechanicalHours={mtbfMechanicalHours}
          mttrMechanicalHours={mttrMechanicalHours}
          mtbfElectricalHours={mtbfElectricalHours}
          mttrElectricalHours={mttrElectricalHours}
          totalDowntimeMinutes={totalDowntimeMinutes}
          repeatFailureRatePct={repeatFailureRatePct}
          availabilityPct={availabilityPct}
          topLossesByDowntime={topLossesByDowntime}
          topLossesByFrequency={topLossesByFrequency}
          chronicVsSporadic={chronicVsSporadic}
          reliabilityByLine={reliabilityByLine}
        />,
      );
      // Two frames: one for React's commit to paint, one to let layout
      // (table row heights etc) settle before html-to-image reads it.
      requestAnimationFrame(() => requestAnimationFrame(() => resolve()));
    });

    const sectionEls = Array.from(hiddenContainer.querySelectorAll<HTMLElement>("[data-pdf-section]"));
    if (sectionEls.length === 0) {
      throw new Error("Nothing to export — no report sections found.");
    }

    const captured: HTMLImageElement[] = [];
    for (let i = 0; i < sectionEls.length; i++) {
      onProgress?.(`Capturing section ${i + 1} of ${sectionEls.length}…`);
      const dataUrl = await toJpeg(sectionEls[i], {
        quality: JPEG_QUALITY,
        pixelRatio: CAPTURE_PIXEL_RATIO,
        backgroundColor: "#ffffff",
      });
      captured.push(await loadImage(dataUrl));
    }

    onProgress?.("Building PDF…");
    const doc = new jsPDF({ unit: "pt", format: "a4" });
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const contentWidth = pageWidth - PAGE_MARGIN * 2;
    const maxContentHeight = pageHeight - PAGE_MARGIN * 2 - FOOTER_HEIGHT;

    let cursorY = PAGE_MARGIN;
    if (logo) {
      doc.addImage(logo.dataUrl, "PNG", PAGE_MARGIN, cursorY, logo.widthPt, logo.heightPt);
    }
    const textX = PAGE_MARGIN + (logo?.widthPt ?? 0) + (logo ? 12 : 0);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text("Maintenance Report", textX, cursorY + 16);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    const periodText = from && to ? `${from} → ${to}` : "All time";
    doc.text(`${lineName} · ${periodText}`, textX, cursorY + 32);
    doc.text(`Generated ${generatedAt.toLocaleString()} by ${generatedBy}`, textX, cursorY + 46);
    cursorY += Math.max(logo?.heightPt ?? 0, 50) + 16;

    for (const img of captured) {
      const pxPerPt = img.width / contentWidth;
      const sectionHeightPt = img.height / pxPerPt;

      if (sectionHeightPt <= maxContentHeight) {
        if (cursorY + sectionHeightPt > pageHeight - PAGE_MARGIN - FOOTER_HEIGHT) {
          doc.addPage();
          cursorY = PAGE_MARGIN;
        }
        doc.addImage(img.src, "JPEG", PAGE_MARGIN, cursorY, contentWidth, sectionHeightPt, undefined, "FAST");
        cursorY += sectionHeightPt + SECTION_GAP;
      } else {
        if (cursorY > PAGE_MARGIN) doc.addPage();
        drawOversizedSection(doc, img, contentWidth, maxContentHeight, pxPerPt);
        cursorY = pageHeight;
      }
    }

    onProgress?.("Adding page numbers…");
    const totalPages = doc.getNumberOfPages();
    for (let p = 1; p <= totalPages; p++) {
      doc.setPage(p);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(120);
      doc.text("Delta Sweets — Production Scorecard OS", PAGE_MARGIN, pageHeight - PAGE_MARGIN + 10);
      doc.text(generatedAt.toLocaleDateString(), pageWidth / 2, pageHeight - PAGE_MARGIN + 10, { align: "center" });
      doc.text(`Page ${p} of ${totalPages}`, pageWidth - PAGE_MARGIN, pageHeight - PAGE_MARGIN + 10, { align: "right" });
      doc.setTextColor(0);
    }

    onProgress?.("Saving file…");
    const dateStr = generatedAt.toISOString().slice(0, 10);
    const safeLine = lineName.replace(/[^a-z0-9]+/gi, "-");
    doc.save(`maintenance-report-${safeLine}-${dateStr}.pdf`);
  } finally {
    root.unmount();
    document.body.removeChild(hiddenContainer);
  }
}
